; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:crowpanel_43]
platform = espressif32@6.13.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
board_upload.flash_size = 4MB
board_build.arduino.partitions = default.csv
board_build.arduino.memory_type = qio_qspi
board_build.psram_type = qio
lib_deps =
  moononournation/GFX Library for Arduino @ 1.5.6
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
build_flags = 
	-DBOARD_HAS_PSRAM
	-DBATTERY_ADC_PIN=-1
	-DBATTERY_DIVIDER_RATIO=2.0f
	-DBATTERY_VOLT_MIN=3.30f
	-DBATTERY_VOLT_MAX=4.20f
